version: 0.2

phases:
  pre_build:
    commands:
      - echo "Pre Build Phase.."
  build:
    commands:
      - echo "Build Phase.."
      - chmod +x ./gradlew
      - ./gradlew build
  post_build:
    commands:
      - echo "Post Build Phase.."
      - echo $(basename ./build/libs/*.jar)
      - pwd

artifacts:
  files:
    - build/libs/*.jar
    - scripts/*.sh
    - appspec.yml
  discard-paths: yes

cache:
  paths:
    - '/root/.gradle/caches/**/*'